# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f52d1299dec7bb893360b15b886c68357f1c4f16f82ec581653da87ab927614ee3f15f89e6317402d3d13252e41d91ba75bb63d5d8fe33af2a3e0d36454bc621

test:
  secret_key_base: 60fd571093a9e4beaa69c488409b0ca1b124ec84faefff6a9b76bd120862feff007144bc5a58d37e01006069fca5a5ce7168d46233139bb051df11d4db90576e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
